CREATE TABLE cars (
    id SERIAL PRIMARY KEY,
    make VARCHAR(50) NOT NULL,    -- brand
    bodytype VARCHAR(50) NOT NULL,
    state VARCHAR(50) NOT NULL CHECK (state IN ('new', 'used', 'accident', 'drowned', 'needs investments')),
    model VARCHAR(50) NOT NULL,
    fuel VARCHAR(20) NOT NULL,
    price FLOAT NOT NULL,         -- euro
    power INT NOT NULL,           -- hp (horsepower)
    torque INT NOT NULL,          -- newton meters (n/m)
    gearbox VARCHAR(20) NOT NULL, -- automate, manual
    color VARCHAR(30),
    upholstery VARCHAR(50),       -- materials for salon
    traction VARCHAR(10) NOT NULL, -- rwd, fwd, awd, 4wd
    purpose VARCHAR(50),          -- purpose of the car
    year INT NOT NULL,            -- manufacturing year
    image_link VARCHAR(255),      -- URL link to an image of the car
    grade SMALLINT CHECK (grade >= 0 AND grade <= 10) -- from 0 to 10
);

INSERT INTO cars (make, bodytype, state, model, fuel, price, power, torque, gearbox, color, upholstery, traction, purpose, year, image_link, grade) VALUES
('Toyota', 'Sedan', 'new', 'Corolla', 'Gasoline', 30000, 203, 250, 'Automatic', 'Red', 'Leather', 'FWD', 'Personal', 2022, 'https://cdn.imagin.studio/getImage?angle=22&billingTag=web&customer=carwow&make=toyota&modelFamily=corolla&modelVariant=estate&modelYear=2024&paintDescription=solid-pure-white&paintId=pspc0323&width=400&zoomLevel=0&zoomType=fullscreen', 7),
('Honda', 'Sedan', 'new', 'Civic', 'Gasoline', 25000, 174, 220, 'Manual', 'Blue', 'Fabric', 'FWD', 'Personal', 2022, 'https://cdn.imagin.studio/getImage?angle=22&billingTag=web&customer=carwow&make=honda&modelFamily=civic&modelRange=civic-hev&modelVariant=ha&modelYear=2022&paintDescription=solid-sonic-grey&paintId=pspc0248&width=400&zoomLevel=0&zoomType=fullscreen', 8),
('Toyota', 'Coupe', 'new', 'Yaris', 'Gasoline', 55000, 450, 410, 'Manual', 'Black', 'Leather', 'FWD', 'Personal', 2022, 'https://cdn.imagin.studio/getImage?angle=22&billingTag=web&customer=carwow&make=toyota&modelFamily=yaris&modelVariant=hatchback&modelYear=2024&paintDescription=metallic-decuma-grey&paintId=pspc0120&width=400&zoomLevel=0&zoomType=fullscreen', 9),
('Suzuki', 'Hatchback', 'new', 'Swace', 'Gasoline', 37000, 200, 360, 'Automatic', 'White', 'Fabric', 'FWD', 'Personal', 2022, 'https://cdn.imagin.studio/getImage?angle=22&billingTag=web&customer=carwow&make=suzuki&modelFamily=swace&modelVariant=estate&modelYear=2024&paintDescription=solid-solid-super-white&paintId=pspc0041&width=400&zoomLevel=0&zoomType=fullscreen', 6),
('Toyota', 'SUV', 'used', 'Yaris Cross', 'Diesel', 20000, 335, 450, 'Automatic', 'Grey', 'Leather', 'AWD', 'Family', 2019, 'https://cdn.imagin.studio/getImage?angle=22&billingTag=web&customer=carwow&make=toyota&modelFamily=yaris-cross&modelVariant=estate&modelYear=2024&paintDescription=solid-pure-white&paintId=pspc0323&width=400&zoomLevel=0&zoomType=fullscreen', 10),
('Honda', 'Sedan', 'new', 'Jazz', 'Gasoline', 16000, 252, 370, 'Automatic', 'Silver', 'Leather', 'FWD', 'Personal', 2022, 'https://cdn.imagin.studio/getImage?angle=22&billingTag=web&customer=carwow&make=honda&modelFamily=jazz&modelVariant=hatchback&modelYear=2025&paintDescription=solid-crystal-black&paintId=pspc0064&width=400&zoomLevel=0&zoomType=fullscreen', 9),
('Mercedes', 'Sedan', 'new', 'C-Class', 'Gasoline', 50000, 255, 400, 'Automatic', 'Black', 'Leather', 'RWD', 'Business', 2022, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=jaguar&filter%5Bmodel_review_slug%5D=xf-2020&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 9),
('Nissan', 'Hatchback', 'drowned', 'Leaf', 'Electric', 20000, 147, 320, 'Automatic', 'Green', 'Fabric', 'FWD', 'Personal', 2021, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=nissan&filter%5Bmodel_review_slug%5D=leaf-2018&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 6),
('Volkswagen', 'Hatchback', 'new', 'Golf', 'Diesel', 29000, 147, 250, 'Manual', 'White', 'Fabric', 'FWD', 'Personal', 2022, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=volkswagen&filter%5Bmodel_review_slug%5D=golf-2019&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 7),
('Kia', 'SUV', 'new', 'Sorento', 'Gasoline', 40000, 290, 350, 'Automatic', 'Black', 'Leather', 'AWD', 'Family', 2022, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=kia&filter%5Bmodel_review_slug%5D=sorento-2020&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 8),
('Mazda', 'SUV', 'new', '3', 'Gasoline',15000, 227, 310, 'Automatic', 'Blue', 'Leather', 'FWD', 'Personal', 2022, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=mazda&filter%5Bmodel_review_slug%5D=3-2019&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 8),
('Porsche', 'Coupe', 'drowned', '911', 'Gasoline', 60000, 379, 450, 'Manual', 'Red', 'Leather', 'RWD', 'Sport', 2020, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=porsche&filter%5Bmodel_review_slug%5D=911-2019&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 10),
('Jaguar', 'Sedan', 'drowned', 'XF', 'Gasoline', 25000, 296, 295, 'Automatic', 'Black', 'Leather', 'RWD', 'Personal', 2020, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=jaguar&filter%5Bmodel_review_slug%5D=xf-2020&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 8),
('Alfa Romeo', 'Sedan', 'new', 'Giulia', 'Gasoline', 25000, 280, 306, 'Automatic', 'White', 'Leather', 'RWD', 'Personal', 2020, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=alfa-romeo&filter%5Bmodel_review_slug%5D=giulia-quadrifoglio&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 8),
('Maserati', 'Sedan', 'used', 'Ghibli', 'Gasoline', 75000, 345, 369, 'Automatic', 'Blue', 'Leather', 'RWD', 'Luxury', 2019, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=maserati&filter%5Bmodel_review_slug%5D=Ghibli&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 9),
('Skoda', 'Sedan', 'new', 'Octavia', 'Gasoline', 25000, 150, 250, 'Automatic', 'Blue', 'Fabric', 'FWD', 'Family', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=skoda&filter%5Bmodel_review_slug%5D=octavia-2017&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 8),
('Toyota', 'SUV', 'used', 'Highlander', 'Gasoline', 50000, 295, 263, 'Automatic', 'Blue', 'Leather', 'AWD', 'Family', 2019, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=toyota&filter%5Bmodel_review_slug%5D=highlander-2021&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 8),
('Honda', 'SUV', 'used', 'CR-V', 'Gasoline', 30000, 190, 179, 'Automatic', 'Blue', 'Leather', 'AWD', 'Family', 2018, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=honda&filter%5Bmodel_review_slug%5D=cr-v-2018&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 8),
('BMW', 'Sedan', 'new', '3 Series', 'Gasoline', 50000, 255, 295, 'Automatic', 'Silver', 'Leather', 'RWD', 'Luxury', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=bmw&filter%5Bmodel_review_slug%5D=3-series-2019&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 9),
('Mercedes-Benz', 'SUV', 'used', 'GLE', 'Gasoline', 75000, 362, 369, 'Automatic', 'White', 'Leather', 'AWD', 'Luxury', 2019, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=mercedes&filter%5Bmodel_review_slug%5D=gle-2019&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 9),
('Ford', 'Hatchback', 'new', 'Focus', 'Gasoline', 20000, 400, 415, 'Automatic', 'White', 'Leather', '4WD', 'Utility', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=ford&filter%5Bmodel_review_slug%5D=focus-estate-2018&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 9),
('Audi', 'SUV', 'new', 'Q8', 'Gasoline', 65000, 335, 365, 'Automatic', 'Black', 'Leather', 'AWD', 'Luxury', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=audi&filter%5Bmodel_review_slug%5D=q8&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 9),
('Nissan', 'Sedan', 'used', 'Qashqai', 'Gasoline', 24000, 188, 244, 'Automatic', 'Blue', 'Fabric', 'FWD', 'Family', 2018, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=nissan&filter%5Bmodel_review_slug%5D=qashqai-2017&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 7),
('Jaguar', 'Sedan', 'used', 'XE', 'Gasoline', 43000, 296, 295, 'Automatic', 'Green', 'Leather', 'AWD', 'Luxury', 2019, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=jaguar&filter%5Bmodel_review_slug%5D=xe-2020&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 8),
('Volkswagen', 'SUV', 'new', 'Tiguan', 'Gasoline', 33000, 184, 221, 'Automatic', 'Red', 'Fabric', 'AWD', 'Family', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=volkswagen&filter%5Bmodel_review_slug%5D=tiguan-2024&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 7),
('Renault', 'Hatchback', 'new', 'Clio', 'Gasoline', 18000, 89, 160, 'Manual', 'Red', 'Fabric', 'FWD', 'Compact', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=renault&filter%5Bmodel_review_slug%5D=Clio&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 7),
('Fiat', 'Hatchback', 'new', '500', 'Electric', 25000, 118, 200, 'Automatic', 'Green', 'Fabric', 'FWD', 'Compact', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=fiat&filter%5Bmodel_review_slug%5D=500&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 8),
('Porsche', 'Hatchback', 'needs investments', 'Cayman', 'Gasoline', 12000, 335, 332, 'Automatic', 'Blue', 'Leather', 'AWD', 'Luxury', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=porsche&filter%5Bmodel_review_slug%5D=Cayman-Old&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 10),
('Tesla', 'Sedan', 'new', 'Model 3', 'Electric', 60000, 283, 307, 'Automatic', 'Black', 'Leather', 'AWD', 'Electric', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=tesla&filter%5Bmodel_review_slug%5D=model-3-2019&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 7),
('Mazda', 'SUV', 'new', 'CX-5', 'Gasoline', 40000, 187, 186, 'Automatic', 'Red', 'Leather', 'AWD', 'Family', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=mazda&filter%5Bmodel_review_slug%5D=cx-5-2017&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 8),
('Skoda', 'SUV', 'new', 'Kodiaq', 'Gasoline', 35000, 190, 320, 'Automatic', 'White', 'Fabric', 'AWD', 'Family', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=skoda&filter%5Bmodel_review_slug%5D=kodiaq-vrs&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 8),
('Peugeot', 'SUV', 'new', '3008', 'Gasoline', 32000, 165, 240, 'Automatic', 'Black', 'Fabric', 'FWD', 'Family', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=peugeot&filter%5Bmodel_review_slug%5D=3008-2023&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 8),
('Renault', 'SUV', 'new', 'Kadjar', 'Gasoline', 31000, 160, 260, 'Automatic', 'Red', 'Fabric', 'FWD', 'Family', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=renault&filter%5Bmodel_review_slug%5D=Kadjar&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150ß', 8),
('Fiat', 'Hatchback', 'new', 'Panda', 'Gasoline', 15000, 85, 145, 'Manual', 'Green', 'Fabric', 'FWD', 'Compact', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=fiat&filter%5Bmodel_review_slug%5D=Panda-New&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 7),
('SEAT', 'Hatchback', 'new', 'Leon', 'Gasoline', 25000, 150, 250, 'Manual', 'Blue', 'Fabric', 'FWD', 'Compact', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=seat&filter%5Bmodel_review_slug%5D=Leon&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 7),
('Citroen', 'SUV', 'new', 'C5 Aircross', 'Gasoline', 34000, 180, 250, 'Automatic', 'Grey', 'Fabric', 'FWD', 'Family', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=citroen&filter%5Bmodel_review_slug%5D=c5-aircross-2019&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 8),
('Jaguar', 'SUV', 'new', 'F-Pace', 'Gasoline', 65000, 340, 450, 'Automatic', 'Black', 'Leather', 'AWD', 'Luxury', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=jaguar&filter%5Bmodel_review_slug%5D=f-pace-2020&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 9),
('Porsche', 'SUV', 'new', 'Cayenne', 'Gasoline', 100000, 460, 620, 'Automatic', 'White', 'Leather', 'AWD', 'Luxury', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=porsche&filter%5Bmodel_review_slug%5D=Cayenne&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 10),
('Audi', 'SUV', 'new', 'A6', 'Gasoline', 39000, 335, 369, 'Automatic', 'Black', 'Leather', 'AWD', 'Family', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=audi&filter%5Bmodel_review_slug%5D=A6-New&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 9),
('BMW', 'SUV', 'new', 'X7', 'Gasoline', 90000, 523, 553, 'Automatic', 'White', 'Leather', 'AWD', 'Luxury', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=bmw&filter%5Bmodel_review_slug%5D=x7&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 9),
('Mercedes-Benz', 'SUV', 'new', 'GLS', 'Gasoline', 85000, 362, 369, 'Automatic', 'Silver', 'Leather', 'AWD', 'Luxury', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=mercedes&filter%5Bmodel_review_slug%5D=gls-2019&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 9),
('Volkswagen', 'SUV', 'new', 'Touareg', 'Diesel', 70000, 231, 500, 'Automatic', 'Green', 'Leather', 'AWD', 'Family', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=volkswagen&filter%5Bmodel_review_slug%5D=touareg-2018&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 9),
('Jaguar', 'SUV', 'new', 'E-Pace', 'Gasoline', 45000, 246, 269, 'Automatic', 'Black', 'Leather', 'AWD', 'Luxury', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=jaguar&filter%5Bmodel_review_slug%5D=e-pace&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 8),
('Skoda', 'Hatchback', 'new', 'Fabia', 'Gasoline', 16000, 95, 160, 'Manual', 'Blue', 'Fabric', 'FWD', 'Compact', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=skoda&filter%5Bmodel_review_slug%5D=Fabia&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 7),
('Peugeot', 'Hatchback', 'new', '208', 'Gasoline', 17000, 100, 190, 'Manual', 'Red', 'Fabric', 'FWD', 'Compact', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=peugeot&filter%5Bmodel_review_slug%5D=208-2019&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 7),
('SEAT', 'Hatchback', 'new', 'Ibiza', 'Gasoline', 16000, 95, 175, 'Manual', 'Blue', 'Fabric', 'FWD', 'Compact', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=seat&filter%5Bmodel_review_slug%5D=ibiza-2017&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 7),
('Citroen', 'Hatchback', 'new', 'C3', 'Gasoline', 15500, 82, 118, 'Manual', 'Grey', 'Fabric', 'FWD', 'Compact', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=citroen&filter%5Bmodel_review_slug%5D=c3-2016&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 7),
('Volkswagen', 'Hatchback', 'new', 'Polo', 'Gasoline', 18000, 110, 200, 'Manual', 'Silver', 'Fabric', 'FWD', 'Compact', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=volkswagen&filter%5Bmodel_review_slug%5D=polo-2017&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 8),
('Dacia', 'SUV', 'new', 'Duster', 'Gasoline', 18000, 115, 156, 'Manual', 'Orange', 'Fabric', 'FWD', 'Family', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=dacia&filter%5Bmodel_review_slug%5D=duster-2018&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 7),
('Dacia', 'Hatchback', 'new', 'Sandero', 'Gasoline', 15000, 90, 140, 'Manual', 'Blue', 'Fabric', 'FWD', 'Compact', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=dacia&filter%5Bmodel_review_slug%5D=sandero-2021&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 7),
('Skoda', 'Hatchback', 'new', 'Scala', 'Gasoline', 19000, 110, 200, 'Manual', 'Red', 'Fabric', 'FWD', 'Compact', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=skoda&filter%5Bmodel_review_slug%5D=scala&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 8),
('Peugeot', 'Hatchback', 'new', '308', 'Gasoline', 20000, 130, 230, 'Manual', 'Black', 'Fabric', 'FWD', 'Compact', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=peugeot&filter%5Bmodel_review_slug%5D=308&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 8),
('Fiat', 'Hatchback', 'new', 'Tipo', 'Gasoline', 17000, 100, 170, 'Manual', 'White', 'Fabric', 'FWD', 'Compact', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=fiat&filter%5Bmodel_review_slug%5D=tipo&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 7),
('Opel', 'Hatchback', 'new', 'Corsa', 'Gasoline', 16000, 100, 170, 'Manual', 'Yellow', 'Fabric', 'FWD', 'Compact', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=vauxhall&filter%5Bmodel_review_slug%5D=corsa-2019&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 7),
('Ford', 'Hatchback', 'new', 'Fiesta', 'Gasoline', 17000, 100, 170, 'Manual', 'Blue', 'Fabric', 'FWD', 'Compact', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=ford&filter%5Bmodel_review_slug%5D=fiesta-2017&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 7),
('Suzuki', 'Hatchback', 'new', 'Swift', 'Gasoline', 16000, 95, 160, 'Manual', 'White', 'Fabric', 'FWD', 'Compact', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=suzuki&filter%5Bmodel_review_slug%5D=swift-2024&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 7),
('Nissan', 'Hatchback', 'new', 'Micra', 'Gasoline', 16000, 100, 160, 'Manual', 'Orange', 'Fabric', 'FWD', 'Compact', 2023, 'https://car-data.carwow.co.uk/image?filter%5Bangle%5D=side&filter%5Bbrand_slug%5D=nissan&filter%5Bmodel_review_slug%5D=micra-2017&zoomType=fullscreen&zoomLevel=0&billingTag=web&width=150', 7);